name: backend-build-test

on:
  push:
    branches:
      - main
      - pipeline


jobs:
  setup-db:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MariaDB container
        id: db-container
        run: |
          # MariaDB-Docker-Container starten
          docker run --name mariadb-container -e MYSQL_ROOT_PASSWORD=my-secret-password -e MYSQL_DATABASE=elinor2 -p 3306:3306 -d mariadb:latest
          # Warten, bis MariaDB bereit ist
          echo "Waiting for MariaDB to start..."
          sleep 15 # Anpassen je nach Bedarf

  build:
    runs-on: ubuntu-latest
    needs: setup-db
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build with Maven
        run: |
          mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Run tests with Maven
        run: mvn test

  cleanup:
    runs-on: ubuntu-latest
    needs: [setup-db, build, test]
    if: always()
    steps:
      - name: Remove MariaDB container
        run: |
          # Stoppen und Entfernen des MariaDB Containers
          docker stop mariadb-container
          docker rm mariadb-container
