name: backend-build-test

on:
  push:
    branches:
      - pipeline


jobs:
  setup-db:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Start MariaDB Container
      - name: Start MariaDB Container
        run: |
          docker run -d \
            --name mariadb \
            -e MYSQL_ROOT_PASSWORD=my-secret-password \
            -e MYSQL_DATABASE=elinor2 \
            -e MYSQL_USER=myuser \
            -e MYSQL_PASSWORD=myuserpassword \
            -p 3306:3306 \
            mariadb:latest

      # Wait for MariaDB to be Ready
      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..10}; do
            if docker exec mariadb mysqladmin ping -u root -pmy-secret-password --silent; then
              echo "MariaDB is ready!"
              exit 0
            fi
            echo "Waiting for MariaDB..."
            sleep 5
          done
          echo "MariaDB did not become ready in time!"
          docker logs mariadb
          exit 1

      # Optional: Check MariaDB Logs
      - name: Check MariaDB Logs
        run: docker logs mariadb

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: ./backend
        run: |
          mvn clean install -DskipTests

      - name: Run tests with Maven
        working-directory: ./backend
        run: mvn test

      - name: Remove MariaDB container
        if: ${{ always() }}
        run: |
          # Stoppen und Entfernen des MariaDB Containers
          docker stop mariadb
          docker rm mariadb
