name: backend-build-test

on:
  push:
    branches:
      - main
      - pipeline


jobs:
  setup-db:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: my-secret-password
          MYSQL_DATABASE: elinor2
          MYSQL_USER: myuser
          MYSQL_PASSWORD: myuserpassword
        options: --health-cmd="mysqladmin ping --silent" --health-start-period=30s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for MariaDB to start
        run: |
          echo "Waiting for MariaDB to start..."
          sleep 30 # Warten, bis MariaDB bereit ist

  build-test:
    runs-on: ubuntu-latest
    needs: setup-db
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: ./backend
        run: |
          mvn clean install -DskipTests

      - name: Run tests with Maven
        working-directory: ./backend
        run: mvn test

      

  cleanup:
    runs-on: ubuntu-latest
    needs: [setup-db, build-test]
    if: always()
    steps:
      - name: Remove MariaDB container
        run: |
          # Stoppen und Entfernen des MariaDB Containers
          docker stop mariadb
          docker rm mariadb
