name: backend-build-test

on:
  push:
    branches:
      - main
      - pipeline


jobs:
  setup-db:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: my-secret-password
          MYSQL_DATABASE: elinor2
          MYSQL_USER: myuser
          MYSQL_PASSWORD: myuserpassword

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build-test:
    runs-on: ubuntu-latest
    needs: setup-db
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: ./backend
        run: |
          mvn clean install -DskipTests

      - name: Run tests with Maven
        working-directory: ./backend
        run: mvn test

      - name: Ping port 3306
        run: |
          if nc -zv localhost 3306; then
            echo "Port 3306 is open."
          else
          echo "Port 3306 is closed."
            exit 1
          fi

      - name: Ping port 3307
        run: |
          if nc -zv localhost 3307; then
            echo "Port 3307 is open."
          else
          echo "Port 3307 is closed."
            exit 1
          fi

      

  cleanup:
    runs-on: ubuntu-latest
    needs: [setup-db, build-test]
    if: always()
    steps:
      - name: Remove MariaDB container
        run: |
          # Stoppen und Entfernen des MariaDB Containers
          docker stop mariadb
          docker rm mariadb
