name: backend-build-test

on:
  push:
    branches:
      - pipeline


jobs:
  setup-db:
    runs-on: ubuntu-latest

    services:
     mariadb:
       image: mariadb:latest
       ports:
         - 3306:3306
       env:
         MYSQL_ROOT_PASSWORD: my-secret-password
         MYSQL_DATABASE: elinor2
         MYSQL_USER: myuser
         MYSQL_PASSWORD: myuserpassword

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4


      # Optional: Check MariaDB Logs
      - name: Check MariaDB Logs
        run: docker logs mariadb

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: ./backend
        run: |
          mvn clean install -DskipTests

      - name: Run tests with Maven
        working-directory: ./backend
        run: mvn test

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove MariaDB container
        if: ${{ always() }}
        run: |
          # Stoppen und Entfernen des MariaDB Containers
          docker stop mariadb
          docker rm mariadb
